using System.ComponentModel;

namespace Everlong.Globalization;

/// <summary>
///   Base class for all INPC-capable typed accessor classes generated by <c>lang gen</c>.
///   Manages the <see cref="INotifyPropertyChanged" /> plumbing and key-prefix resolution so
///   generated subclasses only need to declare string properties.
/// </summary>
public abstract class StringSectionBase : INotifyPropertyChanged
{
  private readonly LangProvider _provider;
  private readonly string _keyPrefix;

  /// <summary>
  ///   Initializes a new section accessor.
  /// </summary>
  /// <param name="provider">The mutable locale provider to delegate lookups to.</param>
  /// <param name="keyPrefix">
  ///   Dot-separated prefix prepended to every local key before calling
  ///   <see cref="LangProvider.GetString" />.
  ///   Pass an empty string (default) when the subclass owns the root key namespace.
  /// </param>
  protected StringSectionBase(LangProvider provider, string keyPrefix = "")
  {
    _provider = provider;
    _keyPrefix = keyPrefix;
    provider.ProviderChanged += Invalidate;
  }

  /// <inheritdoc />
  public event PropertyChangedEventHandler? PropertyChanged;

  private void Invalidate(object? sender, EventArgs eventArgs) =>
    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(null));

  /// <summary>
  ///   Returns the localized string for <paramref name="localKey" />, falling back to
  ///   <paramref name="fallback" /> when the key is missing.
  ///   The full lookup key is <c>&lt;keyPrefix&gt;.&lt;localKey&gt;</c> (or just
  ///   <paramref name="localKey" /> when the prefix is empty).
  /// </summary>
  protected string GetString(string localKey, string fallback = "")
    => _provider.GetString(ResolveKey(_keyPrefix, localKey), fallback);

  private static string ResolveKey(string? prefix, string key) =>
    string.IsNullOrEmpty(prefix) ? key : $"{prefix}.{key}";
}
